name: github-snapshot-release

# Only trigger a SNAPSHOT release to GitHub Packages, when the build workflow succeeded
#on:
#  workflow_run:
#    workflows: ["github-push"]
#    types:
#      - completed
on: [push]
jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up settings.xml for GitHub Packages
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github

    - name: Publish SNAPSHOT version to GitHub Packages (we can skip tests, since we only deploy, if the build workflow succeeded)
      run: mvn -B --no-transfer-progress deploy -DskipTests --projects cxf-spring-boot-starter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}